get:
  operationId: get_configuration
  tags:
    - Zone
  x-onedata-gri:
    type: oz_worker
    aspect: configuration
  x-onedata-permissions: []
  summary: Returns public configuration of Onezone service.
  x-bash-codegen-description: |
    Returns public information about the Onezone service.

    This endpoint does not require authentication.
  description: |
    Returns public information about the Onezone service.

    This endpoint does not require authentication.

    ***Example cURL requests***

    **List all groups in the system**
    ```bash
     curl https://$HOST/api/v3/onezone/configuration
    ```
  produces:
    - application/json
  responses:
    '200':
      description: Configuration returned successfully.
      schema:
        $ref: '#/definitions/Configuration'
    '500':
      description: Internal server Error.
      schema:
        $ref: '#/definitions/Error'
  x-code-samples:
  - lang: Shell
    source: "onezone-rest-cli getConfiguration"
