swagger: '2.0'
basePath: /api/v3/onezone
info:
  $ref: ./info/index.yaml
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml
tags:
  - name: Space
    description: Space related operations
  - name: Group
    description: Group related operations
  - name: User
    description: User related operations
  - name: Provider
    description: Provider related operations
  - name: Handle
    description: Operations for managing Handle system service and identifier generation.
securityDefinitions:
  api_key:
    type: apiKey
    name: X-Auth-Token
    in: header
  basic:
    type: basic
    