swagger: '2.0'
basePath: /api/v3/onezone
info:
  $ref: ./info/index.yaml
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml
tags:
  - name: Zone
    description: Information about the Onezone service
  - name: User
    description: User management
  - name: Group
    description: Group management
  - name: Space
    description: Space management
  - name: Share
    description: Share management
  - name: Provider
    description: Provider management
  - name: Token
    description: Token (access/invite) management
  - name: Handle
    description: Operations for managing Handle system service and identifier generation.
  - name: Handle Service
    description: Handle service management
  - name: Harvester
    description: Harvester management
  - name: Cluster
    description: Cluster management
x-tagGroups:
  - name: Service information
    tags:
      - Zone
  - name: User management
    tags:
      - User
  - name: Group management
    tags:
      - Group
  - name: Space management
    tags:
      - Space
  - name: Share management
    tags:
      - Share
  - name: Provider management
    tags:
      - Provider
  - name: Token management
    tags:
    - Token
  - name: Handle (DOI, PID) management
    tags:
      - Handle
  - name: Handle service management
    tags:
      - Handle Service
  - name: Harvester management
    tags:
      - Harvester
  - name: Cluster management
    tags:
    - Cluster
securityDefinitions:
  # api_key1 is used by Bash generated clients as default
  # header for sending api key
  basic:
    type: basic
  api_key1:
    type: apiKey
    name: X-Auth-Token
    in: header
  api_key2:
    type: apiKey
    # When using this method, the token must be prefixed with 'Bearer '
    name: Authorization
    in: header
security:
  - basic: []
  - api_key1: []
  - api_key2: []
