swagger: '2.0'
basePath: /api/v3/onezone
info:
  $ref: ./info/index.yaml
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml
tags:
  - name: User
    description: Regular user operations
  - name: Users
    description: User management operations
  - name: Group
    description: Group management operations
  - name: Space
    description: Space management operations
  - name: Provider
    description: Provider management operations
  - name: Handle
    description: Operations for managing Handle system service and identifier generation.
x-tagGroups:
  - name: Regular user operations
    tags:
      - User
  - name: User administration
    tags:
      - Users
  - name: Group management
    tags:
      - Group
  - name: Space management
    tags:
      - Space
  - name: Provider management
    tags:
      - Provider
  - name: Handle (DOI, PID) management
    tags:
      - Handle
securityDefinitions:
  api_key:
    type: apiKey
    name: X-Auth-Token
    in: header
  basic:
    type: basic
security:
  - basic: []
  - api_key: []