swagger: '2.0'
basePath: /api/v3/onezone
info:
  $ref: ./info/index.yaml
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml
tags:
  - name: Space
    description: Space related operations
  - name: Group
    description: Group related operations
  - name: User
    description: User related operations
  - name: Provider
    description: Provider related operations  
  - name: Privileges
    description: Operations on Onezone privileges
securityDefinitions:
  api_key:
    type: apiKey
    name: macaroon
    in: header
  basic:
    type: basic
    