swagger: '2.0'
basePath: /api/v3/onezone
info:
  $ref: ./info/index.yaml
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml
tags:
  - name: Zone
    description: Information about the Onezone service
  - name: User
    description: User management operations
  - name: Group
    description: Group management operations
  - name: Space
    description: Space management operations
  - name: Share
    description: Share management operations
  - name: Provider
    description: Provider management operations
  - name: Handle
    description: Operations for managing Handle system service and identifier generation.
  - name: Handle Service
    description: Handle service management operations.
  - name: Cluster
    description: Cluster management operations.
x-tagGroups:
  - name: Service information
    tags:
      - Zone
  - name: User management
    tags:
      - User
  - name: Group management
    tags:
      - Group
  - name: Space management
    tags:
      - Space
  - name: Share management
    tags:
      - Share
  - name: Provider management
    tags:
      - Provider
  - name: Handle (DOI, PID) management
    tags:
      - Handle
  - name: Handle service management
    tags:
      - Handle Service
  - name: Cluster management
    tags:
    - Cluster
securityDefinitions:
  api_key1:
    type: apiKey
    name: X-Auth-Token
    in: header
  api_key2:
    type: apiKey
    name: Macaroon
    in: header
  api_key3:
    type: apiKey
    name: 'Authorization: Bearer'
    in: header
  basic:
    type: basic
security:
  - basic: []
  - api_key: []
