description: Public information about Onezone configuration and version.
type: object
properties:
  name:
    type: string
    description: Onezone's name
  domain:
    type: string
    description: Onezone's cluster domain
  version:
    type: string
    description: Version of this Onezone service
  build:
    type: string
    description: Build number of this Onezone service
  subdomainDelegationSupported:
    type: boolean
    description: If true, registering Oneproviders are allowed to request
      subdomains of the Onezone domain for use as their domains.
  compatibleOneproviderVersions:
    type: array
    description: List of compatible Oneprovider versions
    items:
      type: string
required:
  - name
  - version
  - build
  - subdomainDelegationSupported
  - compatibleOneproviderVersions
