description: Public information about Onezone configuration and version.
type: object
properties:
  name:
    type: string
    description: Onezone's name
  domain:
    type: string
    description: Onezone's cluster domain
  version:
    type: string
    description: Version of this Onezone service
  build:
    type: string
    description: Build number of this Onezone service
  subdomainDelegationSupported:
    type: boolean
    description: If true, registering Oneproviders are allowed to request
      subdomains of the Onezone domain for use as their domains.
  compatibleOneproviderVersions:
    type: array
    description: List of compatible Oneprovider versions
    items:
      type: string
  compatibilityRegistryRevision:
    type: integer
    description: Revision of the compatibility registry enforced by this Onezone service
  supportedIdPs:
    type: array
    description: List of IdPs supported by Onezone
    items:
      type: object
      description: IdP details
      properties:
        id:
          type: string
          description: The identifier of the IdP
        offlineAccess:
          type: boolean
          description: Determines whether given IdP can be used in the offline
            access flow, i.e. Onezone can acquire access tokens in the IdP without
            the user being logged in.
  availableSpaceTags:
    type: object
    description: |
      A map of tag categories and corresponding available tags for each category.

      Space tag is a short keyword or phrase that helps to understand the purpose of a space.
      Tag categories and available tags are arbitrary strings configured by the Onezone admin.
    additionalProperties:
      type: array
      items:
        type: string
        description: Short keywords or phrases that helps to understand the purpose of a space.
required:
  - name
  - domain
  - version
  - build
  - subdomainDelegationSupported
  - compatibleOneproviderVersions
  - compatibilityRegistryRevision
  - supportedIdPs
  - availableSpaceTags
example:
  name: Example zone
  domain: zone.example.com
  version: 21.02.4
  build: g52dbeca23
  subdomainDelegationSupported: true
  compatibleOneproviderVersions:
    - 20.02.1
    - 20.02.2
    - 21.02.4
  compatibilityRegistryRevision: 2022122100
  supportedIdPs:
    - id: google
      offlineAccess: true
    - id: basicAuth
      offlineAccess: false
  availableSpaceTags:
    general:
      - big-data
      - demo
      - open-data
      - simulation
    domains:
      - agriculture
      - forestry
      - justice
      - science