type: object
description: Custom JSON configuration passed to harvester GUI plugin.
properties:
  config:
    type: object
required:
  - config
example:
  config: {
    "typeMapping": [ { "id": 0, "name": "Type 1" }, { "id": 1, "name": "Type 1" } ],
    "externalHelpLink": "http://example.com/some_help_page",
    "refreshDataTimeout": 1000
  }
