get:
  operationId: get_provider_domain_config
  tags:
    - Provider
  x-onedata-gri:
    type: od_provider
    id: ?BINDING(id)
    aspect: domain_config
  summary: Get provider's domain config
  x-onedata-permissions:
    - oz_providers_view
  x-bash-codegen-description: |
    Returns the domain config of specific Oneprovider.

    This operation requires any of the following authentication:
    * as the subject provider (`{id}`),
    * as user who has `cluster_view` privilege in the cluster corresponding to
      the subject provider,
    * as user who has `oz_providers_view` admin privilege.
  description: |
    Returns the domain config of specific provider.

    This operation requires any of the following authentication:
    * as the subject provider (`{id}`),
    * as user who has `cluster_view` privilege in the cluster corresponding to
      the subject provider,
    * as user who has `oz_providers_view` admin privilege.

    ***Example cURL requests***

    **Get provider's domain config**
    ```bash
    curl -sS -u username:password -X GET  \
    https://$ZONE_HOST/api/v3/onezone/providers/$PROVIDER_ID/domain_config

    {
      "subdomainDelegation": true,
      "domain": "provider1.onezone.example.com",
      "subdomain": "provider1",
      "ipList": ["172.17.0.1", "172.17.0.2", "172.17.0.3"]
    }
    ```
  produces:
    - application/json
  responses:
    '200':
      description: The provider's domain config.
      schema:
        $ref: '#/definitions/ProviderDomainConfig'
    '400':
      description: Invalid request.
      schema:
        $ref: '#/definitions/Error'
    '401':
      description: Authentication error.
      schema:
        $ref: '#/definitions/Error'
    '403':
      description: Authorization error.
      schema:
        $ref: '#/definitions/Error'
    '404':
      description: Resource not found.
      schema:
        $ref: '#/definitions/Error'
    '500':
      description: Internal server Error.
      schema:
        $ref: '#/definitions/Error'
  parameters:
    - name: id
      description: Provider Id.
      type: string
      in: path
      required: true
  x-code-samples:
  - lang: Shell
    source: "onezone-rest-cli getProviderDomainConfig id=0f7fa3347bd2f090acc6ed246e1f1747"
